"""
Count the operations of the NN-RL-RMSE model and export it to TensorFlow Lite.

Run on the laptop (needs full TensorFlow):
    python export_and_count.py --model RMSE_RL_1.keras --out tflite_models

Outputs:
    - A per-layer table of multiply-accumulates (MACs) and parameters
    - tflite_models/nn_N{n}_fp32.tflite  and  nn_N{n}_int8.tflite
      (one fixed-shape model per number of candidate networks N)
    - tflite_models/op_count.json
"""
import argparse
import json
import os
import shutil

import numpy as np
import tensorflow as tf

N_VALUES = [1, 5, 10, 17]   # numbers of candidate networks to export


def input_dims(model):
    """Return the last dimension of the protocol, velocity and parameter inputs."""
    dims = {}
    for t in model.inputs:
        for key in ("protocol", "velocities", "inputs"):
            if key in t.name:
                dims[key] = int(t.shape[-1])
    return dims


def count_ops(model, timesteps):
    rows = []
    for layer in model.layers:
        cls = layer.__class__.__name__
        w = layer.get_weights()
        params = layer.count_params()
        if cls == "Dense":
            macs = w[0].shape[0] * w[0].shape[1]
            rows.append((layer.name, cls, macs, params, ""))
        elif cls == "LSTM":
            kernel, recurrent = w[0], w[1]
            per_step = kernel.shape[0] * kernel.shape[1] + recurrent.shape[0] * recurrent.shape[1]
            rows.append((layer.name, cls, timesteps * per_step, params, f"{timesteps} time steps"))
        elif cls == "Embedding":
            rows.append((layer.name, cls, 0, params, "table lookup"))
        elif cls == "BatchNormalization":
            rows.append((layer.name, cls, 0, params, "folded into Dense"))
        elif params > 0:
            rows.append((layer.name, cls, 0, params, "not counted"))
    return rows


def unrolled_copy(model):
    """Same model and weights, with the LSTM unrolled (faster for 3 time steps)."""
    cfg = model.get_config()
    for layer_cfg in cfg["layers"]:
        if layer_cfg["class_name"] == "LSTM":
            layer_cfg["config"]["unroll"] = True
    clone = tf.keras.Model.from_config(cfg)
    clone.set_weights(model.get_weights())
    return clone


def with_protocol_guard(model, dims):
    """Wrap the protocol index into the valid range of the embedding table (index mod 7).
    Identical outputs for valid indices; prevents out-of-range lookups
    (e.g. random inputs generated by the Android benchmark tool)."""
    n_protocols = next(l.input_dim for l in model.layers
                       if l.__class__.__name__ == "Embedding")
    p = tf.keras.Input(shape=(dims["protocol"],), dtype="int32", name="protocol")
    v = tf.keras.Input(shape=(dims["velocities"],), dtype="float32", name="velocities")
    x = tf.keras.Input(shape=(dims["inputs"],), dtype="float32", name="inputs")
    p_safe = tf.keras.layers.Lambda(
        lambda t: tf.keras.ops.mod(t, n_protocols), name="protocol_guard")(p)
    return tf.keras.Model([p, v, x], model([p_safe, v, x]))


def export_tflite(model, dims, n, path, quantize, tmp_dir):
    spec = [
        tf.TensorSpec([n, dims["protocol"]], tf.int32, name="protocol"),
        tf.TensorSpec([n, dims["velocities"]], tf.float32, name="velocities"),
        tf.TensorSpec([n, dims["inputs"]], tf.float32, name="inputs"),
    ]
    saved_dir = os.path.join(tmp_dir, f"saved_N{n}")
    model.export(saved_dir, format="tf_saved_model", input_signature=[spec], verbose=False)
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_dir)
    if quantize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]  # int8 weights
    tflite_model = converter.convert()
    with open(path, "wb") as f:
        f.write(tflite_model)
    return len(tflite_model)


def check_equivalence(model, dims, path, n):
    """Compare Keras and TFLite outputs on random inputs."""
    rng = np.random.default_rng(0)
    p = rng.integers(0, 7, size=(n, dims["protocol"])).astype(np.int32)
    v = rng.uniform(-1, 1, size=(n, dims["velocities"])).astype(np.float32)
    x = rng.uniform(0, 1, size=(n, dims["inputs"])).astype(np.float32)
    ref = model([p, v, x], training=False).numpy()

    interp = tf.lite.Interpreter(model_path=path)
    interp.allocate_tensors()
    for d in interp.get_input_details():
        if d["dtype"] == np.int32:
            interp.set_tensor(d["index"], p)
        elif d["shape"][-1] == dims["velocities"]:
            interp.set_tensor(d["index"], v)
        else:
            interp.set_tensor(d["index"], x)
    interp.invoke()
    out = interp.get_tensor(interp.get_output_details()[0]["index"])
    return float(np.max(np.abs(out - ref)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="RMSE_RL_1.keras")
    ap.add_argument("--out", default="tflite_models")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    model = tf.keras.models.load_model(args.model)
    dims = input_dims(model)
    rows = count_ops(model, dims["velocities"])
    total_macs = sum(r[2] for r in rows)
    total_params = model.count_params()

    print("=" * 78)
    print(f"{'Layer':<24}{'Type':<20}{'MACs':>10}{'Params':>10}  Note")
    print("-" * 78)
    for name, cls, macs, params, note in rows:
        print(f"{name:<24}{cls:<20}{macs:>10,}{params:>10,}  {note}")
    print("-" * 78)
    print(f"{'Total per candidate':<44}{total_macs:>10,}{total_params:>10,}")
    print(f"Parameter memory: {total_params * 4 / 1024:.1f} KB (float32), "
          f"{total_params / 1024:.1f} KB (int8)")
    print("=" * 78)
    print(f"{'N':>4}{'MACs per decision':>22}{'FLOPs per decision':>22}")
    for n in N_VALUES:
        print(f"{n:>4}{n * total_macs:>22,}{2 * n * total_macs:>22,}")
    print("=" * 78)

    deploy_model = with_protocol_guard(unrolled_copy(model), dims)
    tmp_dir = os.path.join(args.out, "_saved_models")
    sizes = {}
    for n in N_VALUES:
        for quant, tag in [(False, "fp32"), (True, "int8")]:
            path = os.path.join(args.out, f"nn_N{n}_{tag}.tflite")
            size = export_tflite(deploy_model, dims, n, path, quant, tmp_dir)
            err = check_equivalence(model, dims, path, n)
            sizes[f"N{n}_{tag}"] = size
            print(f"Exported {path}  ({size / 1024:.1f} KB, max |TFLite - Keras| = {err:.2e})")

    shutil.rmtree(tmp_dir, ignore_errors=True)

    with open(os.path.join(args.out, "op_count.json"), "w") as f:
        json.dump({
            "layers": [{"name": r[0], "type": r[1], "macs": r[2], "params": r[3]} for r in rows],
            "macs_per_candidate": total_macs,
            "params": total_params,
            "input_dims": dims,
            "tflite_sizes_bytes": sizes,
        }, f, indent=2)


if __name__ == "__main__":
    main()
