from .SPMO_Max_Min_Method import SPMO_Max_Min_Method
from .SPMO_Preference import SPMO_Preference
from .MPMO_SAW import MPMO_SAW
from .MPMO_WPM import MPMO_WPM
from .MPMO_TOPSIS import MPMO_TOPSIS
from .MPMO_Fuzzy import MPMO_Fuzzy
from .MPMO_RMSE import MPMO_RMSE
from .NN_TOPSIS import NN_TOPSIS
from .BenchmarkMethod import BenchmarkMethod
from .WorstScenarioMethod import WorstScenarioMethod